import { ConfigProvider } from "antd";
import { Metadata } from "next";
import { FC, ReactNode } from "react";

import "./globals.css";

export const metadata: Metadata = {
  title: "CLUB ERP",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning>
        <ConfigProvider>{children}</ConfigProvider>
      </body>
    </html>
  );
};

export default RootLayout;
