import { FC, ReactNode } from "react";
import { Providers } from "./providers";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "CLUB ERP",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
